

const cars = {
  audi: {
    name:  "Audi A1 S-Line",
    img: "audia1",
    price: 45,
    model: "Audi",
    mark: "A1",
    year: "2012",
    transmission: "Manual",
    fuel: "Gasoline",
  },
  golf: {
    name: "VW Golf 6",
    img: "golf6",
    price: 37,
    model: "golf6",
    mark: "Volkswagen",
    year: "2008",
    transmission: "Manual",
    fuel: "Diesel",
  },
  toyota: {
    name: "Toyota Camry",
    img: "toyotacamry",
    price: 30,
    model: "Camry",
    mark: "Toyota",
    year: "2006",
    transmission: "Automatic",
    fuel: "Hybrid",
  },
  bmw: {
    name: "BMW 320 ModernLine",
    img: "bmw320",
    price: 35,
    model: "320",
    mark: "BMW",
    year: "2012",
    transmission: "Manual",
    fuel: "Diesel",
  },
  mercedes: {
    name: "Mercedes-Benz GLK",
    img: "benz",
    price: 50,
    model: "Benz GLK",
    mark: "Mercedes",
    year: "2006",
    transmission: "Manual",
    fuel: "Diesel",
  },
  passat: {
    name: "VW Passat CC",
    img: "passatcc",
    price: 25,
    model: "Passat CC",
    mark: "Volkswagen",
    year: "2008",
    transmission: "Automatic",
    fuel: "Gasoline",
  },
};

export default cars;